/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\axel-wheel-only.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, useRevoluteJoint, useFixedJoint } from "@react-three/rapier"

export function AxelOnly(props) {
  const frontAxel = useRef()
  const tire1 = useRef()
  const { nodes, materials } = useGLTF('/axel-wheel-only.glb')

  // add a revolute joint here
  

  return (
    <group {...props} dispose={null}>
      <RigidBody ref={frontAxel}>
        <mesh geometry={nodes.AxelFront.geometry} material={materials.blacktrim} position={[0.525, 0, 0]} />
      </RigidBody>

      <mesh geometry={nodes.AxelRear.geometry} material={materials['blacktrim.001']} position={[-0.575, 0, 0]} />
      <mesh geometry={nodes.tire1.geometry} material={materials.blacktrim} position={[0.536, -0.193, -0.479]} rotation={[3.141, -0.006, -1.582]} scale={0.445} />
      <mesh geometry={nodes.shadeWhite_006.geometry} material={nodes.shadeWhite_006.material} position={[0.536, -0.193, -0.479]} rotation={[3.141, -0.006, -1.582]} scale={0.445} />
      <mesh geometry={nodes.tire2.geometry} material={materials.blacktrim} position={[0.535, -0.193, 0.474]} rotation={[0, 0, 1.559]} scale={0.445} />
      <mesh geometry={nodes.shadeWhite_006001.geometry} material={nodes.shadeWhite_006001.material} position={[0.535, -0.193, 0.474]} rotation={[0, 0, 1.559]} scale={0.445} />
      <mesh geometry={nodes.tire3.geometry} material={materials.blacktrim} position={[-0.568, -0.193, 0.474]} rotation={[0, 0, 1.559]} scale={0.445} />
      <mesh geometry={nodes.shadeWhite_006002.geometry} material={nodes.shadeWhite_006002.material} position={[-0.568, -0.193, 0.474]} rotation={[0, 0, 1.559]} scale={0.445} />
      <RigidBody ref={tire1}>
        <mesh geometry={nodes.tire4.geometry} material={materials.blacktrim} position={[-0.567, -0.193, -0.479]} rotation={[3.141, -0.006, -1.582]} scale={0.445} />
        <mesh geometry={nodes.shadeWhite_006003.geometry} material={nodes.shadeWhite_006003.material} position={[-0.567, -0.193, -0.479]} rotation={[3.141, -0.006, -1.582]} scale={0.445} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/axel-wheel-only.glb')
