/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\semi-truck-1.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/semi-truck-1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Truck_cab.geometry} material={materials.Material} position={[0, 2.911, 0]} />
      <mesh geometry={nodes.FR_wheel.geometry} material={materials['wheel color']} position={[-2.617, 0, 7.043]} />
      <mesh geometry={nodes.FL_wheel.geometry} material={materials['wheel color']} position={[2.709, 0, 7.043]} />
      <mesh geometry={nodes.RL_wheel.geometry} material={materials['wheel color']} position={[2.561, 0, -4.204]} />
      <mesh geometry={nodes.RR_wheel.geometry} material={materials['wheel color']} position={[-2.678, 0, -4.204]} />
    </group>
  )
}

useGLTF.preload('/semi-truck-1.gltf')
